### ISSUE TITLE
Define structure for Tasks

### ISSUE THREAD

**Issue by JonathanGzzBen** [JonathanGzzBen/dotmake#2]

**Comment by JonathanGzzBen** [comment]
Proposal:

```yaml
---
task_name:
  type: <type_of_task>
  requires:
    - <required_task_1>
    - <required_task_2>
  arg1: <value_of_arg1>
  arg2:
    - <value_1_of_arg2>
    - <value_2_of_arg2>
```

**Comment by JonathanGzzBen** [comment]
Shell task proposal:
```yaml
---
shell_task_1:
  type: shell
  commands:
    - <command_1>
    - <command_2>

```
